<?php if ( !defined('BASEPATH')) muere('Acceso no permitido');

//----------------------------------------------------------------------------------	
function inicio_controlador( $accion = 'listado' )
{ 
	Vista::layout('_cabecera_dataTable.php' );
	call_user_func( $accion, $params );
}
//----------------------------------------------------------------------------------	
function fin_controlador() 
{
	Vista::layout('pie.php');
}
//----------------------------------------------------------------------------------	
function listado() 
{
	$sql = <<<FIN
	(SELECT 
		(SELECT RTRIM('CICS_T_TRAN_TP') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT VARCHAR_FORMAT(MIN(START_TIMESTAMP), 'DD/MM/YYYY HH24:MI:SS')  FROM DRLP.CICS_T_TRAN_TP) AS DESDE, 
		(SELECT VARCHAR_FORMAT(MAX(START_TIMESTAMP), 'DD/MM/YYYY HH24:MI:SS') FROM DRLP.CICS_T_TRAN_TP) AS HASTA 
	FROM SYSIBM.SYSDUMMY1)
	UNION ALL
	(SELECT 
		(SELECT RTRIM('CICS_TRANSACTION_D') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT VARCHAR_FORMAT(MIN(DATE), 'DD/MM/YYYY') FROM DRLP.CICS_TRANSACTION_D) AS DESDE, 
		(SELECT VARCHAR_FORMAT(MAX(DATE), 'DD/MM/YYYY') FROM DRLP.CICS_TRANSACTION_D) AS HASTA 
	FROM SYSIBM.SYSDUMMY1)
	UNION ALL
	(SELECT 
		(SELECT RTRIM('CICS_TRANSACTION_H') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT VARCHAR_FORMAT(MIN(DATE), 'DD/MM/YYYY') FROM DRLP.CICS_TRANSACTION_H) AS DESDE, 
		(SELECT VARCHAR_FORMAT(MAX(DATE), 'DD/MM/YYYY') FROM DRLP.CICS_TRANSACTION_H) AS HASTA 
	FROM SYSIBM.SYSDUMMY1)
	UNION ALL
	(SELECT 
		(SELECT RTRIM('CICS_TRANSACTION_W') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT VARCHAR_FORMAT(MIN(DATE), 'DD/MM/YYYY') FROM DRLP.CICS_TRANSACTION_W) AS DESDE, 
		(SELECT VARCHAR_FORMAT(MAX(DATE), 'DD/MM/YYYY') FROM DRLP.CICS_TRANSACTION_W) AS HASTA 
	FROM SYSIBM.SYSDUMMY1)
	;
FIN;
/*
	SELECT 
		(SELECT RTRIM('CICS_T_TRAN_TP') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT MAX(START_TIMESTAMP) FROM DRLP.CICS_T_TRAN_TP) AS HASTA, 
		(SELECT MIN(START_TIMESTAMP) FROM DRLP.CICS_T_TRAN_TP) AS DESDE 
	FROM SYSIBM.SYSDUMMY1
	WITH UR;

	(SELECT 
		(SELECT RTRIM('CICS_T_TRAN_TP') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT MAX(START_TIMESTAMP) FROM DRLP.CICS_T_TRAN_TP) AS HASTA, 
		(SELECT MIN(START_TIMESTAMP) FROM DRLP.CICS_T_TRAN_TP) AS DESDE 
	FROM SYSIBM.SYSDUMMY1)
	UNION ALL
	(SELECT 
		(SELECT RTRIM('CICS_TRANSACTION_D') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT MAX(DATE) FROM DRLP.CICS_TRANSACTION_D) AS HASTA, 
		(SELECT MIN(DATE) FROM DRLP.CICS_TRANSACTION_D) AS DESDE 
	FROM SYSIBM.SYSDUMMY1)
	UNION ALL
	(SELECT 
		(SELECT RTRIM('CICS_TRANSACTION_H') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT MAX(DATE) FROM DRLP.CICS_TRANSACTION_H) AS HASTA, 
		(SELECT MIN(DATE) FROM DRLP.CICS_TRANSACTION_H) AS DESDE 
	FROM SYSIBM.SYSDUMMY1)
	UNION ALL
	(SELECT 
		(SELECT RTRIM('CICS_TRANSACTION_W') FROM SYSIBM.SYSDUMMY1) AS TABLA,
		(SELECT MAX(DATE) FROM DRLP.CICS_TRANSACTION_W) AS HASTA, 
		(SELECT MIN(DATE) FROM DRLP.CICS_TRANSACTION_W) AS DESDE 
	FROM SYSIBM.SYSDUMMY1)
*/
	$registros = Conexion::query($sql);
	trace($registros);
#	require('listado.php'); 
}
?>